name: Random Robots - Deploy

on:
  push:
    tags:
      - 'v*' # Trigger only on tags like v1.0.0

permissions:
  packages: write
  contents: write

jobs:
  # ✅ 1. Quality checks: install, lint, test, coverage
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Tests (CI)
        run: npm run test:ci

      - name: Run Tests (Coverage)
        run: npm run test:coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: coverage/

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  # ✅ 2. Build & Push Docker image
  docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: quality # Wait for quality checks to pass
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Extract tag name
        id: set_tag
        run: echo "tag_name=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          TAG=${{ steps.set_tag.outputs.tag_name }}
          docker build -t ghcr.io/manuelentrena/random-robots:$TAG -f docker/dockerfile.prod.yml .

      - name: Push Docker image
        run: |
          TAG=${{ steps.set_tag.outputs.tag_name }}
          docker push ghcr.io/manuelentrena/random-robots:$TAG

  # ✅ 3. GitHub Release with Changelog
  release:
    name: GitHub Release
    runs-on: ubuntu-latest
    needs: [quality, docker] # Wait for both jobs
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install auto-changelog
        run: npm install -g auto-changelog

      - name: Generate Changelog
        run: auto-changelog --commit-limit false -o CHANGELOG.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}/CHANGELOG.md
          repository: manuelentrena/random-robots
          token: ${{ secrets.REGISTRY_TOKEN }}
